[{"name": "test.test_xss.XssTest.test_xss", "status": "errored", "message": "Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 118.0.5993.88 with binary path /opt/google/chrome/google-chrome\nStacktrace:\n#0 0x55ad37c224e3 <unknown>\n#1 0x55ad37951c76 <unknown>\n#2 0x55ad3797f04a <unknown>\n#3 0x55ad3797a4a1 <unknown>\n#4 0x55ad37977029 <unknown>\n#5 0x55ad379b5ccc <unknown>\n#6 0x55ad379b547f <unknown>\n#7 0x55ad379acde3 <unknown>\n#8 0x55ad379822dd <unknown>\n#9 0x55ad3798334e <unknown>\n#10 0x55ad37be23e4 <unknown>\n#11 0x55ad37be63d7 <unknown>\n#12 0x55ad37bf0b20 <unknown>\n#13 0x55ad37be7023 <unknown>\n#14 0x55ad37bb51aa <unknown>\n#15 0x55ad37c0b6b8 <unknown>\n#16 0x55ad37c0b847 <unknown>\n#17 0x55ad37c1b243 <unknown>\n#18 0x7f8f66fc09eb <unknown>\n", "passed": false, "points": ["3.3.1", "3.3.2", "3.3.3", "3.3.4", "3.3.5"], "backtrace": ["  File \"/usr/lib/python3.11/unittest/case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.11/unittest/case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.11/unittest/case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"/home/ropo/pythonkikkailut/mooc/mooc-securing-software-23/part3-16.xss/test/test_xss.py\", line 47, in test_xss\n    driver = webdriver.Chrome(port=self.free_port(), options=options, desired_capabilities=caps)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/ropo/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 84, in __init__\n    super().__init__(\n", "  File \"/home/ropo/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 104, in __init__\n    super().__init__(\n", "  File \"/home/ropo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n", "  File \"/home/ropo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/ropo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n", "  File \"/home/ropo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"]}]